import {Ability, AbilityKey} from "../apps/shared/interfaces/ability.interface";
import {RULES} from "./rules";

export const ABILITIES: Ability[] =
[
    {
        image: 'images/muscle_sticker.png',
        title: 'Walker Texas Ranger',
        key: AbilityKey.REDUCE_WALK_WORKOUT,
        description: 'Reduce distance requirements for most of the walking tasks by 10%',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Run Forest Run',
        key: AbilityKey.REDUCE_RUN_WORKOUT,
        description: 'Reduce distance requirements for most of the running tasks by 10%',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Easy Rider',
        key: AbilityKey.REDUCE_RIDE_WORKOUT,
        description: 'Reduce distance requirements for most of the riding tasks by 10%',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Gym Rat',
        key: AbilityKey.REDUCE_OTHER_WORKOUT,
        description: 'Reduce time requirements for most of the non-walking/running/riding tasks by 10%',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Extra Walker',
        key: AbilityKey.BASE_WALK_EXPERIENCE_BONUS,
        description: 'Each completed Basic walking activity gives 1 extra experience point',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Extra Runner',
        key: AbilityKey.BASE_RUN_EXPERIENCE_BONUS,
        description: 'Each completed Basic running activity gives 1 extra experience point',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Extra Rider',
        key: AbilityKey.BASE_RIDE_EXPERIENCE_BONUS,
        description: 'Each completed Basic riding activity gives 1 extra experience point',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Extra Gym',
        key: AbilityKey.BASE_OTHER_EXPERIENCE_BONUS,
        description: 'Each completed Basic non-walking/running/riding activity gives 1 extra experience point',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Procrastinator',
        key: AbilityKey.TASK_QUEUE_SIZE_BONUS,
        description: 'Increase the maximum number of tasks you can have activated at the same time by 1',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Fortune Teller',
        key: AbilityKey.SEE_FUTURE_CHALLENGE,
        description: 'You can see into future and know what challenge will come up next',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Task Master',
        key: AbilityKey.EXPERIENCE_PER_TASK_BONUS,
        description: 'Each completed task gives 1 extra experience point',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Breakthrough',
        key: AbilityKey.FLAT_EXPERIENCE_BONUS,
        description: 'Immediately get 25 experience points',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },


    {
        image: 'images/muscle_sticker.png',
        title: 'Reset Task',
        key: AbilityKey.RESET_CARD,
        description: 'You can reset any played card so it could be played again',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 10,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Victory point',
        key: AbilityKey.BUY_POINT,
        description: 'Immediately get 1 victory point',
        value: 1,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 10,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Win button',
        key: AbilityKey.BUY_3_POINTS,
        description: 'Immediately get 3 victory points',
        value: 3,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 50,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Rest Day',
        key: AbilityKey.SELL_ENERGY_FULL,
        description: 'Lose full energy to immediately get 3 victory points',
        value: 3,
        energyCost: RULES.ENERGY.MAX,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Energy Shot',
        key: AbilityKey.BUY_ENERGY,
        description: 'Immediately restore 1 energy',
        value: 0,
        energyCost: 0,
        energyReward: 1,
        coinsCost: 10,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Energy Boost',
        key: AbilityKey.BUY_ENERGY_FULL,
        description: 'Immediately restore full energy',
        value: 0,
        energyCost: 0,
        energyReward: RULES.ENERGY.MAX,
        coinsCost: 30,
        coinsReward: 0,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'All In',
        key: AbilityKey.ENERGY_TO_COINS,
        description: 'Spend full energy to get 20 coins',
        value: 0,
        energyCost: RULES.ENERGY.MAX,
        energyReward: 0,
        coinsCost: 0,
        coinsReward: 20,
    },
    {
        image: 'images/muscle_sticker.png',
        title: 'Go Easy',
        key: AbilityKey.REDUCE_BASE_WORKOUT,
        description: 'Reduce distance requirements for most of the tasks by 10%',
        value: 0,
        energyCost: 0,
        energyReward: 0,
        coinsCost: 40,
        coinsReward: 0,
    }
]