export const CONST = {
    STRAVA_BASE: "https://www.strava.com",
    API_PREFIX: "/api",
    COLLECTIONS: {
        PENDING_ACTIVITIES: "pending_activities",
        DETAILED_ACTIVITIES: "detailed_activities",
        COMMANDS: "commands",
        HANDS: "hands",
        ATHLETES: "athletes",
        CARDS: "cards",
        SCORES: "scores",
        CARD_FACTORIES: "card_factories",
        ACHIEVEMENTS: "achievements",
        GAME: "game",
        SESSIONS: "sessions",
        SCHEME: "scheme",
        CHALLENGES: "challenges",
        CHALLENGE_PROGRESS: "challenge_progress",
        PURCHASES: "purchases",
    },
    ACTIVITY_PROPERTIES: {
        DISTANCE: "distance",
        TYPE: "type",
        AVERAGE_SPEED: "average_speed",
        MOVING_TIME: "moving_time",
        ELAPSED_TIME: "elapsed_time",
        START_DATE: "start_date",
        ATHLETE_COUNT: "athlete_count",
        ACHIEVEMENT_COUNT: "achievement_count",
        ELEVATION_GAIN: "total_elevation_gain", // TODO : add visuals on cards
    },
    ACTIVITY_TYPES: {
        RUN: "run",
        RIDE: "ride",
        WALK: "walk",
        OTHER: "other"
    },
    COMPARATORS: {
        GREATER: "greater",
        LESS: "less",
        EQUALS: "equals",
        IN: "in",
        NOT_IN: "notIn"
    },
    GAME_ID: "game1",
    SCHEME_ID: "main",
    COMMENT_LENGTH: 300,
    TIMEZONE: 'Europe/Riga',
    TIMEZONE_OFFSET: 3,
    INVENTORY_DISPLAYED_ITEMS: ['chest', 'perk', 'random_perk'],
}
