import {Currencies} from "../apps/shared/classes/currencies.class";

export const LEVEL_REWARDS: Currencies[] = [
    Currencies.withCoins(4),
    Currencies.withEnergy(1).withCoins(3),
    Currencies.withCoins(5),
    Currencies.withCoins(3),
    Currencies.withEnergy(1).withCoins(5),
    Currencies.withChests(1), // chest
    Currencies.withCoins(4),
    Currencies.withEnergy(1).withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(3),
    Currencies.withEnergy(1).withCoins(5),
    Currencies.withPerks(1).withCoins(4), // perk
    Currencies.withCoins(4),
    Currencies.withEnergy(1).withCoins(4),
    Currencies.withCoins(3),
    Currencies.withCoins(5),
    Currencies.withCoins(3).withEnergy(1),
    Currencies.withChests(1), // chest
    Currencies.withCoins(5),
    Currencies.withEnergy(1).withCoins(4),
    Currencies.withCoins(3),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
    new Currencies(4, 0, 0, 0, 0, 1), // random perk
    Currencies.withCoins(3),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withCoins(4),
    Currencies.withCoins(3),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withChests(1).withCoins(5), // chest
    Currencies.withCoins(3),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withCoins(5),
    Currencies.withCoins(3),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withPerks(1).withCoins(5), // perk
    Currencies.withCoins(3),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withCoins(5),
    Currencies.withCoins(4),
    Currencies.withCoins(3).withEnergy(1),
    Currencies.withChests(1), // chest
    Currencies.withCoins(4),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withCoins(3),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withCoins(10),
    Currencies.withCoins(3),
    Currencies.withCoins(3).withEnergy(1),
    Currencies.withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withPoints(1).withCoins(4),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withCoins(3),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withPoints(1).withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withPoints(1).withCoins(4),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withCoins(3),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withPoints(1).withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withCoins(3),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withPoints(1).withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withCoins(3),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withPoints(1).withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
    Currencies.withCoins(3),
    Currencies.withCoins(4),
    Currencies.withCoins(5).withEnergy(1),
    Currencies.withPoints(1).withCoins(4),
    Currencies.withCoins(5),
    Currencies.withCoins(4).withEnergy(1),
]

