import {Currencies} from "../apps/shared/classes/currencies.class";

export const LEVEL_REWARDS: Currencies[] = [
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withChests(1),
    Currencies.withPoints(1),
    Currencies.withExperience(1),
    Currencies.withPerks(1),
    Currencies.withEnergy(1),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withChests(1),
    Currencies.withExperience(1),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withChests(1),
    Currencies.withExperience(1),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withChests(1),
    Currencies.withExperience(1),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
    Currencies.withCoins(8),
]

